POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Essay Writing 101",
  "author": "Cristhian Benitez",
  "url": "essaywriting.com/",
  "likes": "101"
}



###

GET http://localhost:3003/api/blogs/621671c01bc68c8ae8c7c6db


###


PUT http://localhost:3003/api/blogs/621671c01bc68c8ae8c7c6db
Content-Type: application/json

{
  "title": "Essaaay aaag 101",
  "author": "Craaaistaaaitez",
  "url": "essaating.com/",
  "likes": "101"
}


###
DELETE http://localhost:3003/api/blogs/6210fa553386e07092b52b22
