# Get all persons
GET http://localhost:3001/api/persons

###
# Get person by id
GET http://localhost:3001/api/persons/620fccaea8f9045c4b0f31992

###
# Delete person by id
DELETE http://localhost:3001/api/persons/1

###
# Create person
POST http://localhost:3001/api/persons
Content-Type: application/json

 {
   "name": "Jabaea",
    "number": "754-769-0568"
  }



